streamnative/function-mesh-website

docs/install-function-mesh.md

- update crd download link to v0.1.4.
- use `kubectl create` instead of `apply` since the crd is too large so we can only use `create`.

update version of installation doc

---

versioned_docs/version-0.1.4/connectors/io-crd-config/sink-crd-config.md
versioned_docs/version-0.1.4/connectors/io-crd-config/source-crd-config.md
versioned_docs/version-0.1.4/connectors/run-connector.md
versioned_docs/version-0.1.4/functions/function-crd.md
versioned_docs/version-0.1.5/connectors/io-crd-config/sink-crd-config.md
versioned_docs/version-0.1.5/connectors/io-crd-config/source-crd-config.md
versioned_docs/version-0.1.5/connectors/run-connector.md
versioned_docs/version-0.1.5/functions/function-crd.md
versioned_docs/version-0.1.5/releases/release-note-0-1-5.md

Update docs for FunctionMesh release v0.1.5 and v0.1.4:
Doc update for doc-required PRs (remove logTopic from connector CRD function-mesh#242), (fix NPE when not set AutoAck function-mesh#234)

Update docs for v0.1.4 and v0.1.5 releases

---

docs/function-mesh-worker/function-mesh-worker-overview.md
docs/releases/release-note-0-1-8.md
sidebars.js

Update docs for Function Mesh v0.1.8 release.
Add function Mesh worker service overview doc. This doc has been reviewed technically and editorially through the google doc.
Add release note v0.1.8

Add docs for Function Mesh v0.1.8 release

---

docs/connectors/io-crd-config/sink-crd-config.md
docs/connectors/io-crd-config/source-crd-config.md
docs/function-mesh-worker/deploy-mesh-worker.md
docs/function-mesh-worker/function-mesh-worker-overview.md
docs/functions/function-crd.md
docs/scaling.md
versioned_docs/version-0.1.4/connectors/io-crd-config/sink-crd-config.md
versioned_docs/version-0.1.4/connectors/io-crd-config/source-crd-config.md
versioned_docs/version-0.1.4/functions/function-crd.md
versioned_docs/version-0.1.5/connectors/io-crd-config/sink-crd-config.md
versioned_docs/version-0.1.5/connectors/io-crd-config/source-crd-config.md
versioned_docs/version-0.1.5/functions/function-crd.md
versioned_docs/version-0.1.6/connectors/io-crd-config/sink-crd-config.md
versioned_docs/version-0.1.6/connectors/io-crd-config/source-crd-config.md
versioned_docs/version-0.1.6/functions/function-crd.md
versioned_docs/version-0.1.7/connectors/io-crd-config/sink-crd-config.md
versioned_docs/version-0.1.7/connectors/io-crd-config/source-crd-config.md
versioned_docs/version-0.1.7/functions/function-crd.md
versioned_docs/version-0.1.7/scaling.md
versioned_docs/version-0.1.8/connectors/io-crd-config/sink-crd-config.md
versioned_docs/version-0.1.8/connectors/io-crd-config/source-crd-config.md
versioned_docs/version-0.1.8/function-mesh-worker/deploy-mesh-worker.md
versioned_docs/version-0.1.8/function-mesh-worker/function-mesh-worker-overview.md
versioned_docs/version-0.1.8/functions/function-crd.md
versioned_docs/version-0.1.8/scaling.md

In Function Mesh V0.1.9 release, [secrets are supported](https://github.com/streamnative/function-mesh-worker-service/pull/21). Therefore, update docs for this code PR.
- Update docs for secrets supported on function mesh worker service.
- Related release: latest
- Refine authentication descriptions 
- Related releases: v0.1.5- latest
- Update typos, code format and heading levels:
- Related releases: all releases

Update docs for `secretsMap` option support

---

docs/function-mesh-worker/function-mesh-worker-overview.md
docs/install-function-mesh.md
versioned_docs/version-0.1.10/function-mesh-worker/function-mesh-worker-overview.md
versioned_docs/version-0.1.9/function-mesh-worker/function-mesh-worker-overview.md

Add doc for [PR--verify function mesh v0.1.11-rc3](https://github.com/streamnative/function-mesh-worker-service/pull/141) 
- Update the matrix table between Function Mesh v0.1.11 & Function Mesh worker service versions
- Update the matrix table between Function Mesh v0.1.10 & Function Mesh worker service versions
- Fix typo in Function Mesh v0.1.9 release

[v0.1.11]--Update Function mesh worker version matrix table

---

docs/function-mesh-worker/deploy-mesh-worker.md
versioned_docs/version-0.1.10/function-mesh-worker/deploy-mesh-worker.md

This PR is to update docs for [code PR --support custom labels and annotations in custom config](https://github.com/streamnative/function-mesh-worker-service/pull/84).
- Update Function Mesh Worker service config

[v0.1.11]--Add function mesh worker service config

---

docs/install-function-mesh.md
docs/overview/overview.md
versioned_docs/version-0.1.10/install-function-mesh.md
versioned_docs/version-0.1.10/overview/overview.md
versioned_docs/version-0.1.8/overview/overview.md
versioned_docs/version-0.1.9/install-function-mesh.md
versioned_docs/version-0.1.9/overview/overview.md

This PR is to updated docs for the following code PRs, as well as update some legacy doc issues.
- [ISSUE 315] Move apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1 ([ref](https://github.com/streamnative/function-mesh/pull/328))
- add controller-configs ([ref](https://github.com/streamnative/function-mesh/pull/322))
- Update installation doc (update docs for two code PRs)
- Affected releases: v0.1.9 - v0.1.11)
- Update overview doc (fix legacy doc issue)
- Affected releases: v0.1.8 - v0.1.11)

[v0.1.11]--Update Function Mesh Operator config and supported k8s versions

---

docs/install-function-mesh.md

[FM v0.3.0]add docs for setting up webhook

---

docs/connectors/io-crd-config/sink-crd-config.md
docs/connectors/io-crd-config/source-crd-config.md
docs/functions/function-crd.md

The [Code PR #377](https://github.com/streamnative/function-mesh/pull/377) introduces an annotation, which can be used to specify an object as unmanaged. Therefore, update the doc accordingly.
Add a section "Annotations" in Function, Source, and Sink CRD overview docs.
Function Mesh v0.3.0

[FM v0.3.0]-- Support specifying objects as unmanaged objects

---

docs/connectors/io-crd-config/sink-crd-config.md
docs/connectors/io-crd-config/source-crd-config.md
docs/functions/function-crd.md

Function Mesh v0.6.0 support OAuth2 configs ([code PR #447]( https://github.com/streamnative/function-mesh/pull/447)), therefore add docs accordingly.
- Update the Function / Source / Sink CRD configuration docs

[FMv0.6]--Update docs for OAuth2 configs

---

docs/connectors/io-crd-config/sink-crd-config.md
docs/connectors/io-crd-config/source-crd-config.md
docs/functions/function-crd.md
docs/functions/produce-function-log.md

Function Mesh v0.6.0 support setting log rotation policies ([code PR#463](https://github.com/streamnative/function-mesh/pull/463)), therefore add docs accordingly.
- Update Functions/Sources/Sinks CRD configurations doc
- Add a new section "Set log rotation policies" in the "Produce function logs" document

[FM v0.6.0]--Support log rotation policy

---

docs/connectors/io-crd-config/sink-crd-config.md
docs/connectors/io-crd-config/source-crd-config.md
docs/functions/function-crd.md
docs/scaling.md
versioned_docs/version-0.1.10/scaling.md
versioned_docs/version-0.1.11/scaling.md
versioned_docs/version-0.1.4/scaling.md
versioned_docs/version-0.1.5/scaling.md
versioned_docs/version-0.1.6/scaling.md
versioned_docs/version-0.1.7/scaling.md
versioned_docs/version-0.1.8/scaling.md
versioned_docs/version-0.1.9/scaling.md
versioned_docs/version-0.2.0/scaling.md
versioned_docs/version-0.3.0/scaling.md
versioned_docs/version-0.4.0/scaling.md
versioned_docs/version-0.5.0/scaling.md

Function Mesh v0.6.0 enhanced HAP auto-scaling ([code PR #450]( https://github.com/streamnative/function-mesh/pull/450)), therefore add docs accordingly.
- Function Mesh v0.6.0
- Function/Source/Sink CRD configurations
- Add an item "minReplicas"
- Scaling:
- Restructure the doc and add more examples
- Legacy releases
- Update typos
- change `kunectl` to `kubectl`
- change `maxReplica` to `maxReplicas`

[FM v0.6.0]--Update docs for HPA autoscaling enhancement

---

docs/function-mesh-worker/deploy-mesh-worker.md
docs/function-mesh-worker/function-mesh-worker-overview.md

Function Mesh Worker Service v0.6.0 support using separate auth for each user(only support OAuth2)([code PR #357](https://github.com/streamnative/function-mesh-worker-service/pull/357)), therefore add docs accordingly.
- Update the Function Mesh Worker Service overview docs

[FMv0.6]--Update docs about auth support in Mesh Worker Service

---

sidebars.js
versioned_sidebars/version-0.6.0-sidebars.json

The release note v0.6.0 is not shown in the left navigation panel. Therefore, update the `sidebar.json` files for both the `main` and `v0.6.0` branches.

Update sidebar files to add release note 0.6.0

---

docs/function-mesh-worker/function-mesh-worker-overview.md
versioned_docs/version-0.6.0/function-mesh-worker/function-mesh-worker-overview.md

FM v0.7.0 is released. Therefore, update the version matrix between FM and FM worker service.
- For FM v0.7.0, update the Version matrix section in the Function Mesh Worker service overview doc.
- Fix the version matrix info for FM v0.6.0

[FM v0.7.0]--Update version matrix between FM and FM worker service

---

docs/connectors/io-crd-config/sink-crd-config.md
docs/connectors/io-crd-config/source-crd-config.md
docs/functions/function-crd.md

FM v0.7.0 introduced a config to use the init container to download packages/functions ([PR #411](https://github.com/streamnative/function-mesh/pull/411/)). Therefore, update docs accordingly.
Update Function / Source / Sink CRD configuration docs

[FM v0.7.0]--Use init container to download packages/functions

---

docs/connectors/io-crd-config/sink-crd-config.md
docs/connectors/io-crd-config/source-crd-config.md

For Function Mesh v0.8.0, the [code PR #510](https://github.com/streamnative/function-mesh/pull/510) enables stateful config on connectors. Therefore, update the doc accordingly.
- Update the source CRD configurations
- Update the sink CRD configurations

[FM v0.8.0]--Add doc for enabling stateful config on connectors

---

docs/connectors/io-crd-config/sink-crd-config.md
docs/connectors/io-crd-config/source-crd-config.md
docs/functions/function-crd.md

FM v0.8.0 supports a java option to customize JVM options to configure JVM behaviors better ([code PR](https://github.com/streamnative/function-mesh/pull/484)). Therefore, update docs accordingly.
- Update functions/source/sink CRD configurations

[FM v0.8]--Update docs for Java option support

---

docs/function-mesh-worker/reference/rest-api.md
docs/overview/overview.md
sidebars.js

Function Mesh worker service supports some Functions/Sources/Sinks APIs ([Code PR]( https://github.com/streamnative/function-mesh-worker-service/pull/210)). Therefore, add a document about these REST APIs.
- Add a document "REST APIs" under "Function Mesh Worker > Reference".
- Update the Overview document
- Update the sidebar

[FM v0.8.0]--Add REST API docs for FM worker service

---

docs/connectors/io-crd-config/source-crd-config.md

The [code PR #496](https://github.com/streamnative/function-mesh/pull/496) introduces a `batchSourceConfg` for the source connector. Therefore, update the document accordingly.
- Update the Source CRD configurations doc.

[FM v0.8.0]--Add doc for batchSourceConfig option

---

docs/connectors/io-crd-config/sink-crd-config.md
docs/connectors/io-crd-config/source-crd-config.md
docs/functions/function-crd.md

Function Mesh v0.9.0 supports validating Pulsar configs using Webhook ([code PR #534](https://github.com/streamnative/function-mesh/pull/534)). Therefore, update docs accordingly.
- Add a "messaging" section in Function/Sink/Source CRD configuration document that describes supported pulsar configs.
- Adjust the doc structure due to the new content update

[FM v0.9.0] -- Update docs for validating webhook support for Pulsar config

---

docs/connectors/io-crd-config/sink-crd-config.md
docs/connectors/io-crd-config/source-crd-config.md
docs/functions/function-crd.md
docs/functions/produce-function-log.md
docs/functions/run-function/run-window-function.md
docs/scaling.md
versioned_docs/version-0.5.0/functions/produce-function-log.md
versioned_docs/version-0.6.0/functions/produce-function-log.md
versioned_docs/version-0.6.0/functions/run-function/run-window-function.md
versioned_docs/version-0.6.0/scaling.md
versioned_docs/version-0.7.0/functions/produce-function-log.md
versioned_docs/version-0.7.0/functions/run-function/run-window-function.md
versioned_docs/version-0.7.0/scaling.md
versioned_docs/version-0.8.0/functions/produce-function-log.md
versioned_docs/version-0.8.0/functions/run-function/run-window-function.md
versioned_docs/version-0.8.0/scaling.md
versioned_docs/version-0.9.0/connectors/io-crd-config/sink-crd-config.md
versioned_docs/version-0.9.0/connectors/io-crd-config/source-crd-config.md
versioned_docs/version-0.9.0/functions/function-crd.md
versioned_docs/version-0.9.0/functions/produce-function-log.md
versioned_docs/version-0.9.0/functions/run-function/run-window-function.md
versioned_docs/version-0.9.0/scaling.md

In most of the config docs, we use `--- [number]` (such as --- [1]) to indicate a specific option which will be described in the following body text. However, this will cause an error when users copy the code directory from the doc. Therefore, we use a hashtag before the `--- [number]` (`# --- [number]`) (such as # --- [1]) to avoid such confusion.
- Update the comment format in config docs
- Affected releases: all releases

Fix code comment format

---

docs/functions/function-crd.md
docs/reference/function-mesh-config.md

If the function package file uses the HTTP/HTTPS protocol, users need to have an admin access right to download them. To allow a role user to download HTTP/HTTPS package, FM v0.10.0 brings some code changes ([code PR #556](https://github.com/streamnative/function-mesh/pull/556)). Therefore, update docs accordingly.
Update the **Packages** section in the **Function CRD configurations** document.

[FM v0.10.0]--Support using wget to download HTTP/HTTPS packages

---

docs/function-mesh-worker/function-mesh-worker-overview.md
docs/overview/overview.md
docs/releases/release-note-0-11-0.md
sidebars.js

Function Mesh v0.110.0 is released. In this release, codes are updated for underlying services and no doc-required code PRs are introduced. Therefore, add a doc release and update the Function Mesh worker service version matrix.
- Add doc release note v0.11.0
- Update the version matrix table between Function Mesh v0.11.0 and Function Mesh worker service
- Update the Overview document: add the link to the Doc release note v0.11.0
- Update the `sidebar.json `file

[FM v0.11.0]-- Add doc release note & update FM worker service version matrix

---

docs/connectors/io-crd-config/sink-crd-config.md
docs/connectors/io-crd-config/source-crd-config.md
docs/functions/function-crd.md

Function Mesh v0.12.0 supports multiple PVCs for function ([code PR #605](https://github.com/streamnative/function-mesh/pull/605)). Therefore, update docs accordingly.
- add `spec.volumeClaimTemplates` to Function CRD
- Remove the default value of `spec.replicas`

[FM v0.12.0]--Update for supporting multiple PVCs for Function

---

docs/function-mesh-worker/function-mesh-worker-overview.md
docs/overview/overview.md
docs/reference/crd-config/function-crd.md
docs/releases/release-note-0-13-0.md
sidebars.js

Function Mesh v0.13.0 is released. In this release, codes are updated for underlying services and no doc-required code PRs are introduced. Therefore, add a doc release and update the Function Mesh worker service version matrix table.
- Add doc release note v0.13.0
- Update the version matrix table between Function Mesh v0.13.0 and Function Mesh worker service
- Update the Overview document: add the link to the Doc release note v0.13.0
- Update the `sidebar.json `file
- Fix typos

[FM v0.13.0]-- Add doc release note & update FM worker service version matrix

---

docs/reference/crd-config/function-crd.md
docs/reference/crd-config/sink-crd-config.md
docs/reference/crd-config/source-crd-config.md

Function Mesh v0.14.0 fixed the bug that `CleanupSubscription` option doesn't work, and batch source doesn't cleanup intermediate topic either ([code PR #622](https://github.com/streamnative/function-mesh/pull/622))
Update function/Sink/source CRD configurations

[FM v0.14.0]--Update docs for cleaning up subcription configs

---

docs/function-mesh-worker/function-mesh-worker-overview.md
docs/overview/overview.md
docs/releases/release-note-0-14-0.md
sidebars.js

Function Mesh v0.14.0 is released. Therefore, add a doc release and update the Function Mesh worker service version matrix table.
- Add doc release note v0.14.0
- Update the version matrix table between Function Mesh v0.14.0 and Function Mesh worker service
- Update the Overview document: add the link to the Doc release note v0.14.0
- Update the `sidebar.json `file

[FM v0.14.0]--Update Version matrix & Add Release Notes
