- docs/releases/release-note-0-1-7.md
The doc has been editorially reviewed by Dawn and technically reviewed by Neng and Rui.
> Add release note for Function Mesh v0.1.7 release

- docs/install-function-mesh.md
Signed-off-by: hantmac <hantmac@outlook.com>
- Support more controller manager params for helm charts install
- Add doc for https://github.com/streamnative/function-mesh/pull/339
> support more controller manager params for helm charts install

- docs/releases/release-note-0-1-11.md
- sidebars.js
Add the doc release note and update sidebar.json file for Function Mesh v0.1.11 release.
> [FunctionMesh v0.1.11]-- Add release note

- docs/install-function-mesh.md
- docs/releases/release-note-0-2-0.md
add doc for [code PR #361 ](https://github.com/streamnative/function-mesh/pull/361)
1. update docs for installing Function Mesh Operator with Helm
2. add the v0.2.0 release notes
> Update the docs based on the release v0.2.0

- docs/function-mesh-worker/function-mesh-worker-overview.md
- docs/install-function-mesh.md
Update the version matrix between FM and FM Worker service.
Update incorrect Note format.
> [FM v0.2.0]--Update version matrix between FM and FM Worker service

- docs/functions/function-crd.md
- docs/functions/function-overview.md
- docs/functions/run-function/run-stateful-function.md
- sidebars.js
Function Mesh v0.2.0 supports stateful functions. Therefore, add the doc accordingly.
The following docs are added/updated:
- Pulsar Functions Overview
- Pulsar Functions CRD configurations
- Run Stateful Functions
> [FM v0.2.0]Add docs about the stateful functions

- docs/install-function-mesh.md
- docs/releases/release-note-0-3-0.md
- sidebars.js
Add release note for Function Mesh v0.3.0
Unify writings for cert-manager
> [FM v0.3.0]--Add Release notes for Function Mesh v0.3.0

- docs/functions/run-function/run-stateful-function.md
Update configuration instructions for stateful functions, service validation, etc.
> update stateful function docs

- versioned_docs/version-0.3.0/functions/run-function/run-stateful-function.md
Update configuration instructions for stateful functions, service validation, etc.
> update stateful function docs in v0.3.0

- docusaurus.config.js
- package.json
- yarn.lock
https://github.com/streamnative/streamnative.io/issues/1498
> feat: add google analytics support

- docs/connectors/io-crd-config/sink-crd-config.md
- docs/connectors/io-crd-config/source-crd-config.md
- docs/function-mesh-worker/deploy-mesh-worker.md
- docs/functions/function-crd.md
- versioned_docs/version-0.3.0/function-mesh-worker/deploy-mesh-worker.md
The [Code PR #414](https://github.com/streamnative/function-mesh/pull/414), introduced some TLS configurations. Therefore, update docs accordingly.
- Update the Source/Sink/Function CRD configurations
- Fix some link issues.
> [FM 0.4.0]--Use secret for trust path

- docs/overview/overview.md
- docs/releases/release-note-0-4-0.md
- sidebars.js
- versioned_docs/version-0.2.0/overview/overview.md
- versioned_docs/version-0.3.0/overview/overview.md
Add doc release note for Function Mesh v0.4.0 doc release
- Add Release Note v0.4.0
- Update `sidebar.json` file
- Update the **Overview** doc.
> [FM v0.4.0]--Add Doc release note

- docs/connectors/io-crd-config/sink-crd-config.md
- docs/connectors/io-crd-config/source-crd-config.md
- docs/functions/function-crd.md
for PR https://github.com/streamnative/function-mesh/pull/437
> add a limit on the length of the resource name

- docs/functions/run-function/run-go-function.md
- docs/functions/run-function/run-java-function.md
- docs/functions/run-function/run-python-function.md
> add doc on how to build function images with Buildpacks

- docs/functions/function-crd.md
- docs/functions/produce-function-log.md
- docs/overview/overview.md
- sidebars.js
FM v0.5.0 introduced codes for setting function logs ([code PR #445](https://github.com/streamnative/function-mesh/pull/445)). Therefore, update docs accordingly. 
- Update Function CRD configurations doc
- Update the Overview doc
- Update the `sidebar.json` doc
- Add a new doc "Produce function logs"
> [FM v0.5.0]--Update docs for setting function logs

- docs/overview/overview.md
- docs/releases/release-note-0-5-0.md
- sidebars.js
Add a doc release note about Function Mesh v0.5.0
> [FM v0.5.0]--Add doc release note

- docs/overview/overview.md
- docs/releases/release-note-0-6-0.md
Add a doc release note for doc releases for FM v0.6.0
> [FM v0.6.0]--Add Doc release note

- docs/overview/overview.md
- docs/releases/release-note-0-7-0.md
- sidebars.js
Add a doc release note for Function Mesh v0.7.0 doc release.
- Add the FM v0.7.0 release note
- Update the `sidebar.json` file
- Update the Overview document.
> [FM v0.7.0]-- Add doc release note for Function Mesh v0.7.0

- docs/overview/overview.md
Fix [#499](https://github.com/streamnative/function-mesh/issues/499)
The content in the "Features" section of the "Overview" document is outdated. Therefore, update this doc.
Update the content in the "Features" section of the "Overview" document
Affected release: v0.8.0
> [FM v0.8.0]--Update the outdated content in Overview document

- docs/install-function-mesh.md
FM v0.8.0 bring a flag to enable/disable the init container ([Code PR#515](https://github.com/streamnative/function-mesh/pull/515/)). Therefore, update the doc accordingly.
Update the Installation document.
> [FM v0.8.0]--Update doc for enabling/disablign init container

- docs/overview/overview.md
- docs/releases/release-note-0-8-0.md
- docs/scaling.md
- sidebars.js
Add a doc release note for Function Mesh v0.8.0 doc release.
- Add a Release Note v0.8.0
- Update Overview doc
- Update `sidebar.json` file
- Editorial update for Scaling doc
> [FM v0.8.0]-- Add FM v0.8.0 doc release note

- docs/install-function-mesh.md
- versioned_docs/version-0.7.0/install-function-mesh.md
- versioned_docs/version-0.8.0/install-function-mesh.md
Update docs for the [code PR #542](https://github.com/streamnative/function-mesh/pull/542)
> 504: change installation steps description to make it work

- docs/function-mesh-worker/function-mesh-worker-overview.md
Update the version matrix between Function Mesh & Function Mesh Worker service
> [FM v0.9.0]--Update version Matrix for FM and FM worker service

- docs/connectors/io-crd-config/sink-crd-config.md
- docs/connectors/io-crd-config/source-crd-config.md
- docs/functions/function-crd.md
- docs/reference/function-mesh-config.md
Function Mesh V0.9.0 supports health checks using a liveness probe ([code PR #538](https://github.com/streamnative/function-mesh/pull/538)). Therefore, update docs accordingly.
- Update Source/Sink/Function CRD configurations
- Update Function Mesh Configuration documents
> [FM v0.9.0]--Update docs for health checks

- docs/overview/overview.md
- docs/releases/release-note-0-9-0.md
- sidebars.js
Add a doc release note for Function Mesh v0.9.0.
- Add Release note v0.9.0
- Update the `sidebar.json` file
- Update the **Overview** document
> [Fm v0.9.0]--Add doc release note for FM v0.9.0

- docs/function-mesh-worker/function-mesh-worker-overview.md
Update the version matrix between Function Mesh & Function Mesh Worker service
> [FM v0.10.0]--update version matrix between FM and FM Worker service

- docs/releases/release-note-0-10-0.md
Update release note based on tech review comment on PR #230.
> [FM v0.10]Update Release note

- docs/connectors/io-crd-config/sink-crd-config.md
- docs/connectors/io-crd-config/source-crd-config.md
- docs/functions/function-crd.md
- docs/reference/function-mesh-config.md
Function Mesh v0.12.0 made some fixes on the liveness probe ([code PR #604](https://github.com/streamnative/function-mesh/pull/604)). Therefore, update docs accordingly.
Update the Functions/Sinks/Sources CRD config documentation
> [FM v0.12.0]--Update docs for liveness probe

- docs/function-mesh-worker/function-mesh-worker-overview.md
Update the version matrix between Function Mesh & Function Mesh Worker service
> [FM V12.0]--update version matrix between FM and FM Worker service

- docs/connectors/io-crd-config/sink-crd-config.md
- docs/connectors/io-crd-config/source-crd-config.md
- docs/functions/function-crd.md
Function Mesh v0.12.0 enhanced the Pod security context ([code PR #574](https://github.com/streamnative/function-mesh/pull/574/)). Therefore, update the docs accordingly.
Update Functions, Sinks/Sources CRD configurations.
> [FM v0.12.0]--Update docs for enhanced security context

- docs/reference/crd-config/function-crd.md
Update docs for the Statefulset configs that are brought by code PRs [#633](https://github.com/streamnative/function-mesh/pull/633/) and [#639](https://github.com/streamnative/function-mesh/pull/639).
Update Function CRD configurations
> [FM v0.14.0]--Update docs about statefulset configs

- docs/install-function-mesh.md
- versioned_docs/version-0.1.10/install-function-mesh.md
- versioned_docs/version-0.1.11/install-function-mesh.md
- versioned_docs/version-0.1.4/install-function-mesh.md
- versioned_docs/version-0.1.5/install-function-mesh.md
- versioned_docs/version-0.1.6/install-function-mesh.md
- versioned_docs/version-0.1.7/install-function-mesh.md
- versioned_docs/version-0.1.8/install-function-mesh.md
- versioned_docs/version-0.1.9/install-function-mesh.md
- versioned_docs/version-0.10.0/install-function-mesh.md
- versioned_docs/version-0.11.0/install-function-mesh.md
- versioned_docs/version-0.12.0/install-function-mesh.md
- versioned_docs/version-0.13.0/install-function-mesh.md
- versioned_docs/version-0.14.0/install-function-mesh.md
- versioned_docs/version-0.15.0/install-function-mesh.md
- versioned_docs/version-0.2.0/install-function-mesh.md
- versioned_docs/version-0.3.0/install-function-mesh.md
- versioned_docs/version-0.4.0/install-function-mesh.md
- versioned_docs/version-0.5.0/install-function-mesh.md
- versioned_docs/version-0.6.0/install-function-mesh.md
- versioned_docs/version-0.7.0/install-function-mesh.md
- versioned_docs/version-0.8.0/install-function-mesh.md
- versioned_docs/version-0.9.0/install-function-mesh.md
Fix #271 
- Update the installation guide
- All releases
> Update Installation guide
